[package]
name = "projectrube"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_rapier3d = "0.31.0"
block-mesh = "0.2.0"
fastnoise-lite = "1.1.1"
ndshape = "0.3.0"
winit = "0.30.12"
futures-lite = "2.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
